[tool.poetry]
name = "enem"
version = "0.1.0"
description = ""
authors = ["gabriel almeida <gabriel.almeida@somosyoung.com.br>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
